packageName: Simply.com SDK
invokerPackage: SimplyCom
modelPackage: SimplyCom\Model
apiPackage: SimplyCom\Api
overwrite: true
composerPackageName: simplycom/php-sdk
variableNamingConvention: camelCase
srcBasePath: src
modelDocs: false
apiDocs: false
enablePostProcessFile: true