packageName: SimplyCom-php
invokerPackage: SimplyCom
modelPackage: Model
apiPackage: Api
overwrite: true
composerPackageName: simplycom/php-sdk
variableNamingConvention: camelCase
srcBasePath: src
enablePostProcessFile: true
hideGenerationTimestamp: true
gitUserId: simplycom
gitRepoId: api-php