<?php
/**
 * DnszoneApiTest
 * PHP version 8.1
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SimplyCom\Test\Api;

use SimplyCom\Configuration;
use SimplyCom\ApiException;
use SimplyCom\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DnszoneApiTest Class Doc Comment
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DnszoneApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addDnsRecord
     *
     * Add new DNS record to a product DNS zone.
     *
     */
    public function testAddDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ddnsHelper
     *
     * Dynamic DNS helper endpoint.
     *
     */
    public function testDdnsHelper()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDnsRecord
     *
     * Remove DNS record from a product DNS zone.
     *
     */
    public function testDeleteDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dyndns
     *
     * DynDNS protocol-compatible endpoint.
     *
     */
    public function testDyndns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDnsRecords
     *
     * Retrieve all DNS records for a product.
     *
     */
    public function testGetDnsRecords()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDnsZone
     *
     * Retrieve DNS zone metadata.
     *
     */
    public function testGetDnsZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reloadDnsZone
     *
     * Force-reload a DNS zone.
     *
     */
    public function testReloadDnsZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDnsRecord
     *
     * Update a DNS record in a product DNS zone.
     *
     */
    public function testUpdateDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
