<?php
/**
 * RegistryApiTest
 * PHP version 8.1
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SimplyCom\Test\Api;

use SimplyCom\Configuration;
use SimplyCom\ApiException;
use SimplyCom\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RegistryApiTest Class Doc Comment
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RegistryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getDnssecKeys
     *
     * Retrieve DNSSEC keys registered on a domain.
     *
     */
    public function testGetDnssecKeys()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getNameservers
     *
     * Retrieve the current nameservers of a domain.
     *
     */
    public function testGetNameservers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
