<?php
/**
 * AnyOfInterface
 *
 * PHP version 8.1
 *
 * @package  SimplyCom\Model
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SimplyCom\Model;

/**
 * Interface implemented by models generated from an `anyOf` schema.
 *
 * An `anyOf` schema is not represented by a value object; instead a value is one of the
 * member types. Classes implementing this interface only carry the metadata that
 * {@see ObjectSerializer::deserialize()} needs to resolve the concrete member type.
 *
 * @package SimplyCom\Model
 * @author  OpenAPI Generator team
 */
interface AnyOfInterface
{
    /**
     * List of the types a value of this `anyOf` schema may be. Each entry uses the same
     * notation as the values of {@see ModelInterface::openAPITypes()}.
     *
     * @return string[]
     */
    public static function getAnyOfTypes(): array;

    /**
     * Name of the discriminator property used to resolve the concrete member type, or null
     * when the schema has no discriminator.
     *
     * @return string|null
     */
    public static function getAnyOfDiscriminator(): ?string;

    /**
     * Mapping of discriminator values to the concrete member type. Empty when the schema has
     * no discriminator.
     *
     * @return array<string,string>
     */
    public static function getAnyOfDiscriminatorMappings(): array;
}
