<?php
/**
 * DnsRecordType
 *
 * PHP version 8.1
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SimplyCom\SimplyCom\Model;

/**
 * DnsRecordType Class Doc Comment
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum DnsRecordType: string
{
    case A = 'A';

    case CNAME = 'CNAME';

    case AAAA = 'AAAA';

    case ALIAS = 'ALIAS';

    case MX = 'MX';

    case TXT = 'TXT';

    case NS = 'NS';

    case DS = 'DS';

    case DNSKEY = 'DNSKEY';

    case SRV = 'SRV';

    case SPF = 'SPF';

    case SOA = 'SOA';

    case HTTPS = 'HTTPS';

    case LOC = 'LOC';

    case CAA = 'CAA';

    case SSHFP = 'SSHFP';

    case TLSA = 'TLSA';
}


