<?php
/**
 * GetProductList200ResponseProductsInnerServers
 *
 * PHP version 8.1
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SimplyCom\SimplyCom\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use SimplyCom\ObjectSerializer;

/**
 * GetProductList200ResponseProductsInnerServers Class Doc Comment
 *
 * @description Server information (only present for hosting products)
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class GetProductList200ResponseProductsInnerServers implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'getProductList_200_response_products_inner_servers';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'webserver' => '\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersWebserver',
        'ftpserver' => '\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersFtpserver',
        'sshserver' => '\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersSshserver'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'webserver' => null,
        'ftpserver' => null,
        'sshserver' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'webserver' => false,
        'ftpserver' => false,
        'sshserver' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'webserver' => 'webserver',
        'ftpserver' => 'ftpserver',
        'sshserver' => 'sshserver'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'webserver' => 'setWebserver',
        'ftpserver' => 'setFtpserver',
        'sshserver' => 'setSshserver'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'webserver' => 'getWebserver',
        'ftpserver' => 'getFtpserver',
        'sshserver' => 'getSshserver'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('webserver', $data ?? [], null);
        $this->setIfExists('ftpserver', $data ?? [], null);
        $this->setIfExists('sshserver', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets webserver
     *
     * @return \SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersWebserver|null
     */
    public function getWebserver(): ?\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersWebserver
    {
        return $this->container['webserver'];
    }

    /**
     * Sets webserver
     *
     * @param \SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersWebserver|null $webserver webserver
     *
     * @return $this
     */
    public function setWebserver(?\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersWebserver $webserver): static
    {
        if (is_null($webserver)) {
            throw new InvalidArgumentException('non-nullable webserver cannot be null');
        }
        $this->container['webserver'] = $webserver;

        return $this;
    }

    /**
     * Gets ftpserver
     *
     * @return \SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersFtpserver|null
     */
    public function getFtpserver(): ?\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersFtpserver
    {
        return $this->container['ftpserver'];
    }

    /**
     * Sets ftpserver
     *
     * @param \SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersFtpserver|null $ftpserver ftpserver
     *
     * @return $this
     */
    public function setFtpserver(?\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersFtpserver $ftpserver): static
    {
        if (is_null($ftpserver)) {
            throw new InvalidArgumentException('non-nullable ftpserver cannot be null');
        }
        $this->container['ftpserver'] = $ftpserver;

        return $this;
    }

    /**
     * Gets sshserver
     *
     * @return \SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersSshserver|null
     */
    public function getSshserver(): ?\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersSshserver
    {
        return $this->container['sshserver'];
    }

    /**
     * Sets sshserver
     *
     * @param \SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersSshserver|null $sshserver sshserver
     *
     * @return $this
     */
    public function setSshserver(?\SimplyCom\SimplyCom\Model\GetProductList200ResponseProductsInnerServersSshserver $sshserver): static
    {
        if (is_null($sshserver)) {
            throw new InvalidArgumentException('non-nullable sshserver cannot be null');
        }
        $this->container['sshserver'] = $sshserver;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


