<?php
/**
 * ProductServers
 *
 * PHP version 8.1
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.3.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SimplyCom\SimplyCom\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use SimplyCom\ObjectSerializer;

/**
 * ProductServers Class Doc Comment
 *
 * @package  SimplyCom
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ProductServers implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'ProductServers';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'nameservers' => 'string[]',
        'webserver' => '\SimplyCom\SimplyCom\Model\WebServer',
        'ftpserver' => '\SimplyCom\SimplyCom\Model\FtpServer',
        'sshserver' => '\SimplyCom\SimplyCom\Model\SshServer'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'nameservers' => null,
        'webserver' => null,
        'ftpserver' => null,
        'sshserver' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'nameservers' => false,
        'webserver' => true,
        'ftpserver' => true,
        'sshserver' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'nameservers' => 'nameservers',
        'webserver' => 'webserver',
        'ftpserver' => 'ftpserver',
        'sshserver' => 'sshserver'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'nameservers' => 'setNameservers',
        'webserver' => 'setWebserver',
        'ftpserver' => 'setFtpserver',
        'sshserver' => 'setSshserver'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'nameservers' => 'getNameservers',
        'webserver' => 'getWebserver',
        'ftpserver' => 'getFtpserver',
        'sshserver' => 'getSshserver'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nameservers', $data ?? [], null);
        $this->setIfExists('webserver', $data ?? [], null);
        $this->setIfExists('ftpserver', $data ?? [], null);
        $this->setIfExists('sshserver', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['nameservers'] === null) {
            $invalidProperties[] = "'nameservers' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nameservers
     *
     * @return string[]
     */
    public function getNameservers(): array
    {
        return $this->container['nameservers'];
    }

    /**
     * Sets nameservers
     *
     * @param string[] $nameservers Simply.com nameservers currently assigned to the domain in our system. Does not query the registry.
     *
     * @return $this
     */
    public function setNameservers(array $nameservers): static
    {
        if (is_null($nameservers)) {
            throw new InvalidArgumentException('non-nullable nameservers cannot be null');
        }
        $this->container['nameservers'] = $nameservers;

        return $this;
    }

    /**
     * Gets webserver
     *
     * @return \SimplyCom\SimplyCom\Model\WebServer|null
     */
    public function getWebserver(): ?\SimplyCom\SimplyCom\Model\WebServer
    {
        return $this->container['webserver'];
    }

    /**
     * Sets webserver
     *
     * @param \SimplyCom\SimplyCom\Model\WebServer|null $webserver Web server information (only present for hosting products)
     *
     * @return $this
     */
    public function setWebserver(?\SimplyCom\SimplyCom\Model\WebServer $webserver): static
    {
        if (is_null($webserver)) {
            array_push($this->openAPINullablesSetToNull, 'webserver');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('webserver', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['webserver'] = $webserver;

        return $this;
    }

    /**
     * Gets ftpserver
     *
     * @return \SimplyCom\SimplyCom\Model\FtpServer|null
     */
    public function getFtpserver(): ?\SimplyCom\SimplyCom\Model\FtpServer
    {
        return $this->container['ftpserver'];
    }

    /**
     * Sets ftpserver
     *
     * @param \SimplyCom\SimplyCom\Model\FtpServer|null $ftpserver FTP server information (only present for hosting products)
     *
     * @return $this
     */
    public function setFtpserver(?\SimplyCom\SimplyCom\Model\FtpServer $ftpserver): static
    {
        if (is_null($ftpserver)) {
            array_push($this->openAPINullablesSetToNull, 'ftpserver');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ftpserver', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ftpserver'] = $ftpserver;

        return $this;
    }

    /**
     * Gets sshserver
     *
     * @return \SimplyCom\SimplyCom\Model\SshServer|null
     */
    public function getSshserver(): ?\SimplyCom\SimplyCom\Model\SshServer
    {
        return $this->container['sshserver'];
    }

    /**
     * Sets sshserver
     *
     * @param \SimplyCom\SimplyCom\Model\SshServer|null $sshserver SSH server information (only present for hosting products). Add public-key manually through Simply.com Controlpanel.
     *
     * @return $this
     */
    public function setSshserver(?\SimplyCom\SimplyCom\Model\SshServer $sshserver): static
    {
        if (is_null($sshserver)) {
            array_push($this->openAPINullablesSetToNull, 'sshserver');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sshserver', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sshserver'] = $sshserver;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int|string $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|string|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


