<?php
/**
 * OrderApi
 * PHP version 8.1
 *
 * @package  SimplyCom\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.1.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SimplyCom\Sdk\Api;

use InvalidArgumentException;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use SimplyCom\Sdk\ApiException;
use SimplyCom\Sdk\Configuration;
use SimplyCom\Sdk\HeaderSelector;
use SimplyCom\Sdk\FormDataProcessor;
use SimplyCom\Sdk\ObjectSerializer;

/**
 * OrderApi Class Doc Comment
 *
 * @package  SimplyCom\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'call3db09c5bcfacbbba537a8872997b010e' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation call3db09c5bcfacbbba537a8872997b010e
     *
     * @param  \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest _3db09c5bcfacbbba537a8872997b010eRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return object
     */
    public function call3db09c5bcfacbbba537a8872997b010e(
        \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest,
        string $contentType = self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'][0]
    ): array
    {
        list($response) = $this->call3db09c5bcfacbbba537a8872997b010eWithHttpInfo($_3db09c5bcfacbbba537a8872997b010eRequest, $contentType);
        return $response;
    }

    /**
     * Operation call3db09c5bcfacbbba537a8872997b010eWithHttpInfo
     *
     * @param  \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function call3db09c5bcfacbbba537a8872997b010eWithHttpInfo(
        \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest,
        string $contentType = self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'][0]
    ): array
    {
        $request = $this->call3db09c5bcfacbbba537a8872997b010eRequest($_3db09c5bcfacbbba537a8872997b010eRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        'object',
                        $request,
                        $response,
                    );
            }
            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                'object',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        
            throw $e;
        }
    }

    /**
     * Operation call3db09c5bcfacbbba537a8872997b010eAsync
     *
     * @param  \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function call3db09c5bcfacbbba537a8872997b010eAsync(
        \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest,
        string $contentType = self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'][0]
    ): PromiseInterface
    {
        return $this->call3db09c5bcfacbbba537a8872997b010eAsyncWithHttpInfo($_3db09c5bcfacbbba537a8872997b010eRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation call3db09c5bcfacbbba537a8872997b010eAsyncWithHttpInfo
     *
     * @param  \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function call3db09c5bcfacbbba537a8872997b010eAsyncWithHttpInfo(
        \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest,
        string $contentType = self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'][0]
    ): PromiseInterface
    {
        $returnType = 'object';
        $request = $this->call3db09c5bcfacbbba537a8872997b010eRequest($_3db09c5bcfacbbba537a8872997b010eRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'call3db09c5bcfacbbba537a8872997b010e'
     *
     * @param  \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function call3db09c5bcfacbbba537a8872997b010eRequest(
        \SimplyCom\Sdk\Model\3db09c5bcfacbbba537a8872997b010eRequest $_3db09c5bcfacbbba537a8872997b010eRequest,
        string $contentType = self::contentTypes['call3db09c5bcfacbbba537a8872997b010e'][0]
    ): Request
    {

        // verify the required parameter '_3db09c5bcfacbbba537a8872997b010eRequest' is set
        if ($_3db09c5bcfacbbba537a8872997b010eRequest === null || (is_array($_3db09c5bcfacbbba537a8872997b010eRequest) && count($_3db09c5bcfacbbba537a8872997b010eRequest) === 0)) {
            throw new InvalidArgumentException(
                'Missing the required parameter $_3db09c5bcfacbbba537a8872997b010eRequest when calling call3db09c5bcfacbbba537a8872997b010e'
            );
        }


        $resourcePath = '/my/order/dnsservice';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($_3db09c5bcfacbbba537a8872997b010eRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($_3db09c5bcfacbbba537a8872997b010eRequest));
            } else {
                $httpBody = $_3db09c5bcfacbbba537a8872997b010eRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
