<?php
/**
 * DnsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SimplySDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SimplySDK\Test\Api;

use \SimplySDK\Configuration;
use \SimplySDK\ApiException;
use \SimplySDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DnsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SimplySDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DnsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addDnsRecord
     *
     * Add new DNS record to a product DNS zone.
     *
     */
    public function testAddDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ddnsHelper
     *
     * .
     *
     */
    public function testDdnsHelper()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDnsRecord
     *
     * Removes DNS record from a product DNS zone.
     *
     */
    public function testDeleteDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for dyndns
     *
     * .
     *
     */
    public function testDyndns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDnsZone
     *
     * .
     *
     */
    public function testGetDnsZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for reloadDnsZone
     *
     * Force-reload a DNS zone - Usually not necessary.
     *
     */
    public function testReloadDnsZone()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDnsRecord
     *
     * Updates a DNS record in a product DNS zone.
     *
     */
    public function testUpdateDnsRecord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
