<?php
/**
 * ServerStatusApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SimplySDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SimplySDK\Test\Api;

use \SimplySDK\Configuration;
use \SimplySDK\ApiException;
use \SimplySDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServerStatusApiTest Class Doc Comment
 *
 * @category Class
 * @package  SimplySDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServerStatusApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getServerStatusMessages
     *
     * Retrieve a list of current and past serverstatus messages.
     *
     */
    public function testGetServerStatusMessages()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
