<?php
/**
 * AddDnsRecord200ResponseRecordInnerTest
 *
 * PHP version 8.1
 *
 * @package  SimplyCom\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.1.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SimplyCom\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AddDnsRecord200ResponseRecordInnerTest Class Doc Comment
 *
 * @description AddDnsRecord200ResponseRecordInner
 * @package     SimplyCom\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AddDnsRecord200ResponseRecordInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AddDnsRecord200ResponseRecordInner"
     */
    public function testAddDnsRecord200ResponseRecordInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
