<?php
/**
 * 3db09c5bcfacbbba537a8872997b010eRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SimplyCom\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SimplyCom\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * 3db09c5bcfacbbba537a8872997b010eRequestTest Class Doc Comment
 *
 * @category    Class
 * @description 3db09c5bcfacbbba537a8872997b010eRequest
 * @package     SimplyCom\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class 3db09c5bcfacbbba537a8872997b010eRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "3db09c5bcfacbbba537a8872997b010eRequest"
     */
    public function test3db09c5bcfacbbba537a8872997b010eRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "domainaction"
     */
    public function testPropertyDomainaction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "coupon"
     */
    public function testPropertyCoupon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "authid"
     */
    public function testPropertyAuthid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "autorenew"
     */
    public function testPropertyAutorenew()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
