<?php
/**
 * GetServerStatusMessages200ResponseMessagesInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SimplyCom\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Simply.com API
 *
 * Documentation for this API can be found on https://www.simply.com/docs/api/
 *
 * The version of the OpenAPI document: 2.1.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SimplyCom\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * GetServerStatusMessages200ResponseMessagesInnerTest Class Doc Comment
 *
 * @category    Class
 * @description GetServerStatusMessages200ResponseMessagesInner
 * @package     SimplyCom\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetServerStatusMessages200ResponseMessagesInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "GetServerStatusMessages200ResponseMessagesInner"
     */
    public function testGetServerStatusMessages200ResponseMessagesInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dateStart"
     */
    public function testPropertyDateStart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dateEnd"
     */
    public function testPropertyDateEnd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
